require_relative "./greek_gods/version"
require_relative "./greek_gods/cli"
require_relative "./greek_gods/god"
require_relative "./greek_gods/scraper"
require "nokogiri"
require "open-uri"
require "pry"